CPR_VERSION = 1.11.2
CPR_SITE = $(call github,libcpr,cpr,$(CPR_VERSION))
CPR_LICENSE = MIT
CPR_LICENSE_FILES = LICENSE

CPR_INSTALL_STAGING = YES
CPR_DEPENDENCIES = libcurl

CPR_CONF_OPTS = \
	-DCPR_FORCE_USE_SYSTEM_CURL=ON \
	-DCPR_BUILD_TESTS=OFF

$(eval $(cmake-package))
