NLOHMANN_JSON_VERSION = v3.11.3
NLOHMANN_JSON_SITE = $(call github,nlohmann,json,$(NLOHMANN_JSON_VERSION))
NLOHMANN_JSON_LICENSE = MIT
NLOHMANN_JSON_LICENSE_FILES = LICENSE.MIT

NLOHMANN_JSON_INSTALL_STAGING = YES

NLOHMANN_JSON_CONF_OPTS = \
	-DJSON_BuildTests=OFF

$(eval $(cmake-package))
